### ISSUE TITLE
Add `golangci-lint`

### ISSUE THREAD

**Issue by iamrajiv** [viniciusbds/navio#32]
## Description

`golangci-lint` is a fast Go linters runner. It runs linters in parallel, uses caching, supports `yaml` config, has integrations with all major IDE, and has dozens of linters included.

## References

https://golangci-lint.run/

**Comment by iamrajiv** [comment]
@viniciusbds I want to work on this.

**Comment by viniciusbds** [comment]
Ok @iamrajiv, welcome to the project and feel free to contribute
